{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kured.fullname" . }}
  labels:
    {{- include "kured.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
  selector:
    {{- include "kured.labels" . | nindent 4 }}
{{- end }}