image:
  repository: weaveworks/kured
  tag: 1.4.0
  pullPolicy: IfNotPresent
  pullSecrets: []

extraArgs: {}

rbac:
  create: true

podSecurityPolicy:
  create: false

serviceAccount:
  create: true
  name:

updateStrategy: OnDelete

priorityClassName: ""

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

affinity: {}

nodeSelector: {}

podAnnotations: {}
