name: Publish helm chart
on:
  push:
    branches:
      - "master"
    paths:
      - "charts/**"

jobs:
  publish-helm-chart:
    name: Publish latest chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
