name: "Shellcheck"
on: [pull_request]

jobs:
  bash-lint:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: bewuethr/shellcheck-action@v2
